# Generated by Django 4.0.2 on 2022-04-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_about_us_slider_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
