# Generated by Django 4.0.2 on 2022-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_about_us_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
