# Generated by Django 4.0.2 on 2022-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_pin_code_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
